# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe22f4af967bc92d06b978b7f589846b937fc40b18a0c83431d7e7044da8e8c96a007b77c5221099f9de99fc50fa23fc5cc01b375893609a409f97f236d46d6

test:
  secret_key_base: 52ad1783c153e6ad476ee7a4e7b0f4f5ee7df2f1161135d9c5b6c2046a113ad607f5aecfd53199d5b68f6de4a3492a60a57dd88c04db267220cd57183541e242

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
